use_frameworks!

pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'MMDrawerController', '~> 0.5.7'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Alamofire', '~> 3.0'
pod 'BetterSegmentedControl', '~> 0.1'
