platform :ios, '10.0'

use_frameworks!

target "SomeApp" do
    #    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Messaging'
    pod 'Firebase/Auth'
    pod 'Alamofire', '~> 5.0.0-rc.3'
    pod 'BetterSegmentedControl', '~> 1.2' # to support Swift 5.0

    #pod 'ScryptoString'#, :path => '../../ScryptoString-Pod'
    #pod 'LPMessagingSDK'
    pod 'OnGestureSwift' #, :path => '../../OnGestureSwift-Pod'
    pod 'SwiftKeychainWrapper', '~> 3.4'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5.0'
            end
        end
    end
    
end
